### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by enenH** [SsageParuders/Android_Native_Surface#2]
建议添加个获取屏幕转向和屏幕尺寸
https://android.googlesource.com/platform/frameworks/native/+/refs/heads/master/opengl/tests/lib/WindowSurface.cpp

**Comment by SsageParuders** [comment]
后期是有这个考虑 开放更多的AOSP中API出来

---

就目前而言的话 获取屏幕尺寸和感知屏幕旋转 是通过Native层代码新开一个线程持续判断的
https://github.com/SsageParuders/Android_Native_Surface/blob/d1f2f24bf638c12454422701bff8560b1f9980da/src/Android_draw/draw.cpp#L89-L109

不过显然可以有更完善的做法 后续再更新

---

现在的项目是我在放假前 用学校的电脑跑完的编译

当时匆促 很多地方没来得及改 就放假了

我现在手头上没有合适的开发机(手头上就一台MacBookPro 不适合开虚拟机拉AOSP 太大了)

项目目前还是有很多地方存在问题 有待优化的 

暂时只是提供思路原理 可供参考

后面回校 再持续完善 拓展兼容性等等

**Comment by SsageParuders** [comment]
请见 [中文说明](https://github.com/SsageParuders/Android_Native_Surface/blob/master/Chinese.md)
