### ISSUE TITLE
部分手机运行黑屏

### ISSUE THREAD

**Issue by baipiaoguai123** [SsageParuders/Android_Native_Surface#6]
部分手机运行以后黑屏是什么问题

**Comment by SsageParuders** [comment]
这个问题不是AOSP库的问题

貌似是我EGL和IMGUI配置什么地方写的不太好

还在查 会尽快修复

**Comment by cduang** [comment]
你好，我也遇到了这个问题，设备：小米8SE，安卓10。程序编译运行后，能正常显示imgui菜单窗口，但是在菜单窗口外部，手机屏幕全是黑色，似乎有一个外部的窗口覆盖。

**Comment by SsageParuders** [comment]
> 你好，我也遇到了这个问题，设备：小米8SE，安卓10。程序编译运行后，能正常显示imgui菜单窗口，但是在菜单窗口外部，手机屏幕全是黑色，似乎有一个外部的窗口覆盖。

已经发现这个问题 会尽快修复

如果可以的话 能留个联系方式 协助我调试么

我暂时没有安卓10的设备 目前在凭空修复

可以加TG Group

**Comment by cduang** [comment]
> 

好的，非常乐意能够帮助协调测试(^_^)v，TG @chavvs

**Comment by SsageParuders** [comment]
已经发现问题 

纠正前面的回复 问题就是出在aosp的动态库上面

会尽快修复

**Comment by SsageParuders** [comment]
已修复
