### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by 77132421** [SsageParuders/Android_Native_Surface#8]
动态库添加接口设置窗口flags属性和标题名称

**Comment by SsageParuders** [comment]
有这个考虑 后续会更新

**Comment by 77132421** [comment]
这样可以过录屏

**Comment by 77132421** [comment]
还有就是屏幕翻转ui就不见了

**Comment by SsageParuders** [comment]
> 这样可以过录屏

全机型通杀过录屏（Native Surface），我这里已经实验成功了

不过不是通过设置标题名称 来和ROM的特殊API（例如MIUI）做匹配 实现过滤录屏的

不过不管怎么说 这些AOSP的接口确实很有必要添加上去 我后续会更新

屏幕翻转也会处理

等我这段时间空下来

**Comment by 77132421** [comment]
能否将弄好的发出来一下先

**Comment by 77132421** [comment]
主要是aosp环境麻烦

**Comment by SsageParuders** [comment]
我最近会着手维护 先不急

主要是最近确实比较忙

**Comment by SsageParuders** [comment]
请见 [中文说明](https://github.com/SsageParuders/Android_Native_Surface/blob/master/Chinese.md)
